In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first='True')

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independant=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independant

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependant=dataset[['charges']]

In [10]:
dependant

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion': ['squared_error', 'absolute_error'],
              'max_features': [None, 'sqrt', 'log2'],
              'n_estimators': [10, 100]}
rf = RandomForestRegressor(random_state=42)

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    refit=True,
    verbose=3,
    n_jobs=-1
    )

grid.fit(independant, dependant)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [18]:
GridSearchCV(cv=5, error_score='raise',
             estimator=RandomForestRegressor(criterion='squared_error', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             random_state=None,
                                             n_estimators=rf), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],'max_features': [None, 'sqrt', 'log2'],'n_estimators': [100, 200]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,scoring=None, verbose=3)

GridSearchCV(cv=5, error_score='raise',
             estimator=RandomForestRegressor(max_features=None,
                                             n_estimators=RandomForestRegressor(random_state=42)),
             n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [100, 200]},
             verbose=3)

In [15]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_ #print(re)

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.086814,0.008365,0.007741,0.002678,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.838307,0.749771,0.853935,0.815145,0.824530,0.816338,0.035766,9
1,0.766778,0.025295,0.028954,0.006687,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.849914,0.769660,0.855520,0.818034,0.836538,0.825933,0.030958,5
2,0.064719,0.008153,0.007477,0.000817,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.841356,0.761206,0.846692,0.816064,0.819777,0.817019,0.030320,7
3,0.520926,0.024153,0.029669,0.005733,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857119,0.777528,0.861781,0.831710,0.837814,0.833190,0.030040,1
4,0.070921,0.005137,0.008363,0.001445,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.841356,0.761206,0.846692,0.816064,0.819777,0.817019,0.030320,7
5,0.468183,0.010286,0.017930,0.001157,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857119,0.777528,0.861781,0.831710,0.837814,0.833190,0.030040,1
6,0.242970,0.009611,0.006161,0.002656,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.825770,0.763423,0.832861,0.815793,0.822235,0.812016,0.024914,12
7,2.480406,0.057408,0.027896,0.007326,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.840204,0.769511,0.847333,0.822967,0.834120,0.822827,0.027830,6
8,0.142391,0.012410,0.005647,0.001043,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.841578,0.763818,0.845578,0.805900,0.821656,0.815706,0.029616,10
9,1.382079,0.016124,0.020047,0.002422,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.858640,0.777452,0.859385,0.829946,0.839108,0.832906,0.029952,3
10,0.151490,0.005433,0.005818,0.000506,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.841578,0.763818,0.845578,0.805900,0.821656,0.815706,0.029616,10
11,1.318065,0.034288,0.018083,0.002334,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.858640,0.777452,0.859385,0.829946,0.839108,0.832906,0.029952,3

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 44
BMI: 32
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[8709.9268295]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(