In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first='True')

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independant= dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independant

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependant=dataset[['charges']]
dependant

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independant, dependant, test_size=0.30, random_state=0)

In [11]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [13]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],
            'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid, refit=True, verbose=3, n_jobs=-1)

#fitting the model under the grid search
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [15]:
GridSearchCV(estimator=SVR(), n_jobs=-1,
param_grid={'C': [10, 100, 1000, 2000, 3000],
            'gamma': ['auto', 'scale'],
            'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [16]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.153953,0.025219,0.062426,0.006035,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,35
1,0.109701,0.007243,0.022469,0.001933,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,32
2,0.133664,0.005506,0.030566,0.001194,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,34
3,0.104962,0.006916,0.020437,0.002084,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
4,0.136176,0.003937,0.063867,0.004119,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,36
5,0.100802,0.003677,0.020591,0.001838,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,31
6,0.129312,0.004326,0.027287,0.001405,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,33
7,0.103699,0.006795,0.020831,0.001514,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
8,0.119746,0.005061,0.063011,0.002203,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,29
9,0.114043,0.004793,0.020853,0.000671,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,21
10,0.129554,0.004525,0.027224,0.001890,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,24
11,0.126402,0.006406,0.019635,0.001155,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
12,0.129078,0.005871,0.063409,0.002301,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,30
13,0.114241,0.006257,0.024250,0.003951,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,22
14,0.139144,0.006586,0.026678,0.001373,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,23
15,0.123572,0.006141,0.018842,0.001138,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
16,0.155260,0.005325,0.063404,0.004006,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,12
17,0.159839,0.026054,0.021580,0.001359,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
18,0.146998,0.008368,0.027564,0.003055,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,28
19,0.148196,0.009847,0.020105,0.000568,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
20,0.155026,0.005471,0.062238,0.001576,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,11
21,0.172909,0.041500,0.021276,0.001917,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
22,0.146790,0.010407,0.027314,0.001042,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,27
23,0.143245,0.005575,0.019956,0.001044,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
24,0.167087,0.002565,0.064076,0.001464,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
25,0.280248,0.053004,0.022332,0.001505,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
26,0.146862,0.007621,0.026965,0.001444,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,38
27,0.176331,0.015679,0.021847,0.002053,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
28,0.175330,0.007279,0.063052,0.002022,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
29,0.247643,0.026806,0.022733,0.002584,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
30,0.153124,0.008041,0.028554,0.002694,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,37
31,0.180638,0.016336,0.020975,0.001261,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
32,0.191112,0.005264,0.064211,0.002639,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
33,0.411157,0.215186,0.020029,0.001936,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
34,0.151045,0.012396,0.027602,0.002736,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,39
35,0.212166,0.019838,0.020783,0.001631,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13
36,0.187647,0.018802,0.061208,0.003089,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
37,0.507565,0.188350,0.022014,0.007388,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
38,0.184787,0.033534,0.031706,0.008915,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,40
39,0.250003,0.050021,0.018209,0.002041,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13

In [19]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 32
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [22]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,!change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[643923.34826884]